### ISSUE TITLE
Suggestions on some related tools and review papers

### ISSUE THREAD

**Issue by Zhen-Miao** [mdozmorov/scATAC-seq_notes#2]
Dear Prof. Dozmorov, 

Thanks for your collection of single cell ATAC tools and papers! This is such a cool collection. 

Here I'd like to share some of the works from me and Dr. Junhyong Kim on single cell multiome and preprocessing of scATAC-seq.

1. We also have a review of computational methods for scATAC-seq / scRNA-seq integrative analysis. Our review highlighted the high-level frameworks for the computational integration of data across modalities. Here is the link:
[https://www.nature.com/articles/s41581-021-00463-x](https://www.nature.com/articles/s41581-021-00463-x) 
2. We have a preprocessing tool for single cell ATAC-seq data quantification, [PIC](https://github.com/Zhen-Miao/PIC-snATAC), and we discussed whether there is quantitative information from scATAC-seq data, and here is the bioRxiv preprint:
[https://www.biorxiv.org/content/10.1101/2022.04.20.488960v1](https://www.biorxiv.org/content/10.1101/2022.04.20.488960v1). 

I hope you find these relevant and of interest to target audience of your collection, and consider including them in your repository. Thank you in advance and please let me know if you want any additional details about these two articles.

Best regards,
Zhen Miao
University of Pennsylvania, Perelman School of Medicine

**Comment by mdozmorov** [comment]
Thank you, Zhen, will read and add both.
